openapi: "3.0.0"

# スキーマの情報
info:
  title: TODO API Document
  version: "0.0.1"
  description: TODO API のドキュメントです

# サーバ情報
# [詳細](https://www.alpha.co.jp/blog/202208_02#servers%E3%83%95%E3%82%A3%E3%83%BC%E3%83%AB%E3%83%89)
servers:
  - url: http://localhost:8080

# 分類分け
tags:
  - name: opts
    description: 運用監視関連のAPI
  - name: tasks
    description: タスク関連のAPI

# エンドポイント
paths:
  /health:
    get:
      tags:
        - opts
      responses:
        "200":
          description: OK
  /tasks/1:
    get:
      tags:
        - tasks
      operationId: showTask # メソッド名を任意に命名できるフィールド
      responses:
        "200":
          description: OK
